---
driver:
  name: ec2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: ../data_bags/

verifier:
  name: inspec

platforms:
  - name: aws-base-al2

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: