---
driver:
  name: docker
  provision_command: curl -L https://www.chef.io/chef/install.sh | bash

transport:
  name: docker

provisioner:
  name: chef_zero
  data_bags_path: ../data_bags/

verifier:
  name: inspec

platforms:
  - name: amazon2

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: