---
driver:
  name: ec2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: ../data_bags/

verifier:
  name: inspec

platforms:
  - name: aws-base-al2
    driver:
      image_search:
        owner-id: '899991151204'
        name: COUPA_BASE_AL2_es6.1.p2_hvm_EBS

suites:
  - name: default
    run_list:
      - recipe[lamp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes: